### ISSUE TITLE
Modded Ores

### ISSUE THREAD

**Issue by ghost** [nfinit-gaming/Nether-Metals#16]
So I can't add modded ores into my Nether without adding yet another type of ore generator? Why do the vanilla ones work without it? I was hoping I could just add config lines in for the modded ores we need, to no avail.

**Comment by dshadowwolf** [comment]
All of the BaseMetals/ModernMetals/EndMetals/NetherMetals system use MMD OreSpawn for spawning their ores. For the current stable, 1.x branch of OreSpawn the config files for it are in config/orespawn and are a set of JSON files with the options pretty self-explanatory.

For the development branch available on Curseforge (2.x - currently 2.0.0.15, IIRC) it is just 'orespawn' in the main directory, outside of the config directory. The format of the JSON has changed a little, but not that much.

This has been done to simplify the code in the various *metal mods and centralize the ore generation so that there are less places a bug could be hiding in that code, making it easier to maintain and fix. I can talk to Knox about this, but this move is across this whole branch of the MMD projects.

**Comment by ghost** [comment]
Do I need to switch to an earlier version of OreSpawn? I added it and still can't figure out why no modded metals are showing up. Or do I need Base Metals/Modern Metals also? If so, I'd really like to avoid cluttering my worlds with unnecessary metals...

**Comment by jriwanek** [comment]
Currently you need to use 1.1.0, you can edit the json's generated in config/orespawn to remove any you don't want to generate
