### ISSUE TITLE
Not able to smelt/"crush" nether ores.

### ISSUE THREAD

**Issue by L33T-B33T** [nfinit-gaming/Nether-Metals#72]
Nether ores such as the nether diamond ore have no use and arent able to be completely harvested. JEI shows that MMDLib allows for these ores to be crushed, but there is nothing that allows for that.

**Comment by dshadowwolf** [comment]
We register them with EnderIO and IC2 directly and since the one major API change, Thermal Expansion has had compat for them built in. I will have to do some testing if this isn't working - in the mean time, there is the "crack hammer" that comes with BaseMetals and ModernMetals that can do the job, usually...

**Comment by L33T-B33T** [comment]
Oh! I had no idea about the crack hammer. "Crush" and crack didn't ring
together I suppose. Thank you so much, and I actually just installed TE and
that works as you said. Sorry for the confusion!

**Comment by dshadowwolf** [comment]
they are called "crusher" recipes because the storage of them is also used by (when we manage to get it ported) the 'Advantage' series, and they have a "crusher" :)
